title: "East Coast: Home to the Sunny Side!"
url: https://eastcoast.pa.gov.sg
favicon: /images/favicon-isomer.ico
colors:
  primary-color: "#f0bc42"
  secondary-color: "#9b9b9b"
  media-colors:
    - title: media-color-one
      color: "#f0bc42"
    - title: media-color-two
      color: "#9b9b9b"
    - title: media-color-three
      color: "#f0bc42"
    - title: media-color-four
      color: "#9b9b9b"
    - title: media-color-five
      color: "#f0bc42"
description: Official Website of East Coast GRC
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d2thuhgvaz74co.amplifyapp.com
prod: https://master.d2thuhgvaz74co.amplifyapp.com
facebook-pixel: ""
shareicon: /images/East_Coast_Buzz_logo__1_.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: justin
